resources:
- name: puppet-toughen
  type: git
  source: 
    uri: https://github.com/shearn89/puppet-toughen.git
    branch: develop

jobs:
- name: run-unit-tests
  plan:
  - get: puppet-toughen
    trigger: true
  - task: run-tests
    file: puppet-toughen/ci/test.yml
