resources:
- name: ci-code
  type: git
  source: 
    uri: https://github.com/shearn89/toughen-ci.git

- name: puppet-code
  type: git
  source: 
    uri: https://github.com/shearn89/puppet-toughen.git

- name: toughen-centos
  type: docker-image
  source:
      repository: 172.17.0.1:5000/toughen-centos

jobs:
- name: build-images
  plan:
    - get: ci-code
      trigger: true
    - put: toughen-centos
      params:
        build: ci-code/concourse/dockerfiles
        dockerfile: ci-code/concourse/dockerfiles/centos-Dockerfile

- name: run-tests
  plan:
  - get: puppet-code
    trigger: true
  - get: toughen-centos
    passed: [build-images]
  - task: run-rake
    config:
      platform: linux
      image: centos-image
      inputs:
      - name: puppet-code
      run:
        path: bash
        args: 
        - "-c"
        - cd puppet-toughen && bundle install && bundle exec rake test
