mod 'puppetlabs-stdlib'
mod 'puppetlabs-firewall'
mod 'puppetlabs-limits'
mod 'thias-sysctl'
mod 'puppetlabs-ntp'
mod 'herculesteam-augeasproviders_core'
mod 'herculesteam-augeasproviders_grub'
mod 'kemra102-auditd'
mod 'puppetlabs-concat', '2.2.1'
mod 'puppet-selinux', '0.8.0'

mod 'shearn89/toughen',
    :git => 'https://github.com/shearn89/puppet-toughen',
    :branch => 'develop'
