# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "shearn89/centos7"

  # config.vm.box = "toughen_centos73_virtualbox-iso"
  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "./reports", "/home/vagrant/reports"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: "sudo yum update -y"
  config.vm.provision "shell", path: "scripts/02-get-release-tarball.sh", name: "download toughen release"
end
