# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "shearn89/centos7"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "./reports", "/home/vagrant/reports"
  config.vm.synced_folder "./scripts", "/home/vagrant/scripts"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: "yum update -y"
  config.vm.provision "shell", path: "scripts/01-setup-r10k.sh", name: "configure r10k"
  config.vm.provision "shell", path: "scripts/02-setup-scanner.sh", name: "install oscap scanner"
  config.vm.provision "file", source: "Puppetfile", destination: "Puppetfile"
  config.vm.provision "shell", path: "scripts/03-deploy-modules.sh", name: "deploy modules", privileged: false
  config.vm.provision "file", source: "scripts/99-run-puppet.sh", destination: "run-puppet.sh"
  config.vm.provision "file", source: "site.pp", destination: "site.pp"
  Vagrant.configure("2") do |c|
    c.vm.provision "puppet",
      manifest_file: "site.pp",
      manifests_path: "/home/vagrant/",
      module_path: "/home/vagrant/modules",
      working_directory: "/home/vagrant",
      options: "-v"
  end

end
